spring:
  application:
    name: spring-cloud-eureka-client

server:
  port: 8063

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2 
    hostname: spring-cloud-eureka-client
    preferIpAddress: true #this was done for example purposes only
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
          defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5  